### ISSUE TITLE
No compatible farming mod found.

### ISSUE THREAD

**Issue by ghost** [Montandalar/foodblocks#1]
This mod giving me this error, eventhough I use Minetest Game, which has farming already.
With Farming Redo it works, farming_undo don't know because I don't find it, but only with farming from Minetest Game I get this error.

ModError: Failed to load and run script from \Minetest-win64\bin\..\mods\foodblocks\init.lua:
...\Minetest-win64\bin\..\mods\foodblocks\init.lua:104: No compatible farming mod found! Please install one of the compatible mods:
Farming from Minetest Game, farming_redo by Tenplus1, farming_undo by Felfa or
mcl_farming from Mineclone2.
stack traceback:
	[C]: in function 'error'
	...\Minetest-win64\bin\..\mods\foodblocks\init.lua:104: in main chunk

**Comment by Montandalar** [comment]
Oops! I must never have properly tested vanilla MTG. It should be fixed in the new version 1.2.2 - see [tags](https://github.com/Montandalar/foodblocks/tags). Should be on ContentDB soon too.

**Comment by ghost** [comment]
Well I might be one of the very few people that don't use farming mods that go into mapgen/dungeon loot.

And I downloaded it from the link you posted, it works, and shows the blueberry and apple block, while in the mod menu Foodblocks is written small (foodblocks) and I have technical names disabled. While the old versions mod.conf has this here...

name = foodblocks
optional_depends = default, farming, mcl_farming, ethereal
description = Solid cubes of food for mass storage or building.
release = 13105
author = Blockhead
title = Foodblocks

...the downloaded one from the link only has...

name = foodblocks
optional_depends = default, farming, mcl_farming, ethereal
description = Solid cubes of food for mass storage or building.

...which explains the small written Foodblocks name.

But otherwise it works now. Thank you.

**Comment by Montandalar** [comment]
Ah, thank you for pointing out that I had a lot of data entered on ContentDB that didn't transfer into the direct git download version. I have added that and released 1.2.3 to ContentDB (only change from 1.2.2 was metadata, no actual code change).
