### ISSUE TITLE
Not findable in Minetest engine mod download list.

### ISSUE THREAD

**Issue by ghost** [Montandalar/foodblocks#2]
Hello again.

Don't know if this is a engine problem, or if something happen while updating, but when I wanted to download it from within the Minetest Engine, it's not listed, not on one of the 3 pages when searching for food, and no listing at all when searching foodblocks.

Side note: By the next update fixing this, I don't want to be mentioned in the release notes.

**Comment by Montandalar** [comment]
Hmmm, it's on page 2 of food for me. 

![2024-07-04-004109_1015x632_scrot](https://github.com/Montandalar/foodblocks/assets/13659694/4bc6eb75-a4b3-4c69-a9fc-459cb0580db3)

I won't mention you in further update notes as per your request :)

**Comment by ghost** [comment]
@Montandalar 
And by me it's not there.
Minetest 5.8.0

I see now, if you search with all packages, you find it, but under mods it's not there, which was not the case before.

**Comment by Montandalar** [comment]
Sorry, I made another mistake in making 1.2.3 and had accidentally filed foodblocks as a game instead of a mod. That's why it wouldn't show up when searching for mods. 1.2.4 fixes that.

**Comment by ghost** [comment]
Well, right now not able to look again, but it's good that its fixed. :D

Well not belonging in this Issue, but I ask here now instead of opening a new Issue for it.
Is it okay to suggest one more mod to support, eventhough it's a mod that can still add more fruits?

**Comment by Montandalar** [comment]
Sure, you can always make a suggestion.

**Comment by ghost** [comment]
Well good to know, but I leave it like that for now, because the mod I wanted to mention is still a WIP. ;)

It's nice to know that more suggestions are possible. :)

**Comment by Montandalar** [comment]
You can make any later suggestion in a new thread, this one is taken care of.
