### ISSUE TITLE
Missing red and yellow pepper to block recipes.

### ISSUE THREAD

**Issue by ghost** [Montandalar/foodblocks#3]
Hello,

I noticed that the red pepper in farming redo, has no recipe for the red pepper block.

farming:pepper_red
foodblocks:capsicum_r_cube

Same for the yellow pepper, it has no recipe for the yellow pepper block.

farming:pepper_yellow
foodblocks:capsicum_y_cube

That's all.

**Comment by Montandalar** [comment]
Ah, the item name is different in farming redo from farming undo. I added logic to pick the right item name. The recipes now exist regardless of mods and the drops are now fixed. Releasing v1.2.5.

**Comment by Montandalar** [comment]
Fixed in 1.2.5

**Comment by BlockAndPixelAge** [comment]
Is this logic thing in the settings? Similar to the blueberry setting?

**Comment by Montandalar** [comment]
No, there's no logic decision to be made. Either you have Farming Redo or Farming Undo, you can't have both. The blueberry setting exists because you can concurrently have wild blueberries and farming blueberries.

**Comment by ghost** [comment]
Good to know. So that they don't conflict with each other, when uncrafting or mining the block.
